


export const filesChecklistData = [
    { id: 1, title: 'Complete File Checklist', isChecked: false },
    { id: 2, title: 'Passport Copies on File (6-mth expiry)', isChecked: false },
    { id: 3, title: 'Credit Card Authorization Form', isChecked: false },
    { id: 4, title: 'Active or Retired Military', isChecked: false },
    { id: 5, title: 'Insurance (Country Requirements)', isChecked: false },
    { id: 6, title: 'Frequent Traveller & Loyalty Numbers', isChecked: false },
    { id: 7, title: 'Visas Required', isChecked: false },
    { id: 8, title: 'Residency', isChecked: false },
    { id: 9, title: 'Advised to Check with Family Dr.', isChecked: false },
    { id: 10, title: 'Seat Selection', isChecked: false },
    { id: 11, title: 'Frequent Flyer Program Added', isChecked: false },
    { id: 12, title: 'Connectors', isChecked: false },
    { id: 13, title: 'Stopover Hotel', isChecked: false },
    { id: 14, title: 'Car Rental', isChecked: false },
    { id: 15, title: 'Advised Passport Requirements', isChecked: false },
    { id: 16, title: 'Advised Visa Requirements', isChecked: false },
    { id: 17, title: 'International Driver\'s Permit Required', isChecked: false },
    { id: 18, title: 'Foreign Currency Advised', isChecked: false },
    { id: 19, title: 'Transfers Required', isChecked: false },
    { id: 20, title: 'Hotel/Condo Fees', isChecked: false },
    { id: 21, title: 'Tourist Card', isChecked: false },
    { id: 23, title: 'Departure Tax', isChecked: false },
    { id: 24, title: 'Parent/Child Authorization Form Required', isChecked: false },
    { id: 25, title: 'Requested Document Format', isChecked: false },
    { id: 26, title: 'Documents Available Date', isChecked: false },
    { id: 27, title: 'Final Documents Sent', isChecked: false },
    { id: 28, title: 'Special Requests Added', isChecked: false },
    { id: 29, title: 'Prepaid Gratuities', isChecked: false },
    { id: 30, title: 'Information to be Contacted While Away', isChecked: false },
    { id: 31, title: 'Emergency Contact', isChecked: false },
    { id: 32, title: 'Additional Amenities Offered', isChecked: false },
    { id: 33, title: 'Dining Times', isChecked: false },
    { id: 34, title: 'Dining Table Size', isChecked: false },
    { id: 35, title: 'Lounge Purchase Offered', isChecked: false },
    { id: 36, title: 'Dietary Restrictions/Special Needs', isChecked: false },
  ];
  
export const marketingChecklistData = [
    { id: 1, title: 'Marketing Permission', isChecked: false },
    { id: 2, title: 'Added to Email List', isChecked: false },
    { id: 3, title: 'Closed Client Facebook Group', isChecked: false },
    { id: 4, title: 'First Thank you for Your Business Sent', isChecked: false },
    { id: 5, title: 'Final Payment Reminder Set', isChecked: false },
    { id: 6, title: 'Promotional Item Given', isChecked: false },
    { id: 7, title: 'Bon Voyage Email Sent', isChecked: false },
    { id: 8, title: 'Check-In During Vacation', isChecked: false },
    { id: 9, title: 'Welcome Home Email', isChecked: false },
    { id: 10, title: 'Reminder Set for Yearly Follow Up', isChecked: false },
    { id: 11, title: 'Reminder Set for Documents', isChecked: false },
    { id: 12, title: 'Reminder Set for Trip Check-In', isChecked: false },
  ];
  