export const mockData = [
    {
      id: 1,
      clientName: 'Alice Johnson',
      clientEmail: 'alice.johnson@example.com',
      clientPhone: '555-1234',
      clientPostalCode: 'A1B 2C3',
      clientStreetAddress: '123 Main St',
      clientCity: 'Somewhere',
      clientProvince: 'AB',
      clientCountry: 'Canada',
      notes: 'Loves outdoor activities.',
      invoiced: true,
      paid: false,
      paymentDate: '',
      finalPaymentDate: '',
      dateCreated: '2024-09-15',
      bookings: [
        {
          id: 1,
          travelDate: '2024-10-15',
          clientFinalPaymentDate: '2024-10-01',
          supplierFinalPaymentDate: '2024-10-05',
          bookingDate: '2024-09-16',
          invoicedDate: '2024-09-17',
          confirmationNumbers: [{ confirmationNumber: 'CONF001', supplier: 'Adventure Co.' }],
          namesDateOfBirths: [{ name: 'Alice Johnson', dateOfBirth: '1990-06-10' }],
          mailingAddress: '123 Main St, Somewhere, AB',
          phoneNumbers: ['555-1234'],
          emailAddresses: ['alice.johnson@example.com'],
          significantDates: [],
          bookingId: '2024-10-07T21:51:02.452Z',
        },
        {
          id: 1,
          travelDate: '2024-11-10',
          clientFinalPaymentDate: '2024-11-01',
          supplierFinalPaymentDate: '2024-11-05',
          bookingDate: '2024-09-20',
          invoicedDate: '2024-09-21',
          confirmationNumbers: [{ confirmationNumber: 'CONF002', supplier: 'Camping Co.' }],
          namesDateOfBirths: [{ name: 'Alice Johnson', dateOfBirth: '1990-06-10' }],
          mailingAddress: '123 Main St, Somewhere, AB',
          phoneNumbers: ['555-1234'],
          emailAddresses: ['alice.johnson@example.com'],
          significantDates: [],
          bookingId: '2024-10-07T21:51:03.123Z',
        },
      ],
    },
    {
      id: 2,
      clientName: 'Bob Smith',
      clientEmail: 'bob.smith@example.com',
      clientPhone: '555-5678',
      clientPostalCode: 'B2C 3D4',
      clientStreetAddress: '456 Second St',
      clientCity: 'Anywhere',
      clientProvince: 'BC',
      clientCountry: 'Canada',
      notes: 'Prefers relaxing beach vacations.',
      invoiced: false,
      paid: false,
      paymentDate: '',
      finalPaymentDate: '',
      dateCreated: '2024-09-20',
      bookings: [
        {
          id: 2,
          travelDate: '2024-12-01',
          clientFinalPaymentDate: '2024-11-15',
          supplierFinalPaymentDate: '2024-11-20',
          bookingDate: '2024-09-21',
          invoicedDate: '2024-09-22',
          confirmationNumbers: [{ confirmationNumber: 'CONF003', supplier: 'Beach Resort' }],
          namesDateOfBirths: [{ name: 'Bob Smith', dateOfBirth: '1985-03-25' }],
          mailingAddress: '456 Second St, Anywhere, BC',
          phoneNumbers: ['555-5678'],
          emailAddresses: ['bob.smith@example.com'],
          significantDates: [],
          bookingId: '2024-10-07T21:51:04.456Z',
        },
        {
          id: 2,
          travelDate: '2025-01-15',
          clientFinalPaymentDate: '2024-12-30',
          supplierFinalPaymentDate: '2024-12-31',
          bookingDate: '2024-09-22',
          invoicedDate: '2024-09-23',
          confirmationNumbers: [{ confirmationNumber: 'CONF004', supplier: 'Tropical Getaway' }],
          namesDateOfBirths: [{ name: 'Bob Smith', dateOfBirth: '1985-03-25' }],
          mailingAddress: '456 Second St, Anywhere, BC',
          phoneNumbers: ['555-5678'],
          emailAddresses: ['bob.smith@example.com'],
          significantDates: [],
          bookingId: '2024-10-07T21:51:05.789Z',
        },
      ],
    },
    {
      id: 3,
      clientName: 'Charlie Brown',
      clientEmail: 'charlie.brown@example.com',
      clientPhone: '555-9012',
      clientPostalCode: 'C3D 4E5',
      clientStreetAddress: '789 Third St',
      clientCity: 'Nowhere',
      clientProvince: 'MB',
      clientCountry: 'Canada',
      notes: 'Enjoys cultural trips.',
      invoiced: true,
      paid: false,
      paymentDate: '',
      finalPaymentDate: '',
      dateCreated: '2024-09-25',
      bookings: [
        {
          id: 3,
          travelDate: '2024-10-20',
          clientFinalPaymentDate: '2024-10-10',
          supplierFinalPaymentDate: '2024-10-15',
          bookingDate: '2024-09-26',
          invoicedDate: '2024-09-27',
          confirmationNumbers: [{ confirmationNumber: 'CONF005', supplier: 'Cultural Tours' }],
          namesDateOfBirths: [{ name: 'Charlie Brown', dateOfBirth: '1992-08-14' }],
          mailingAddress: '789 Third St, Nowhere, MB',
          phoneNumbers: ['555-9012'],
          emailAddresses: ['charlie.brown@example.com'],
          significantDates: [],
          bookingId: '2024-10-07T21:51:06.012Z',
        },
      ],
    },
    {
      id: 4,
      clientName: 'Diana Prince',
      clientEmail: 'diana.prince@example.com',
      clientPhone: '555-3456',
      clientPostalCode: 'D4E 5F6',
      clientStreetAddress: '101 First Ave',
      clientCity: 'Gotham',
      clientProvince: 'ON',
      clientCountry: 'Canada',
      notes: 'Adventurous and loves nature.',
      invoiced: true,
      paid: true,
      paymentDate: '2024-09-29',
      finalPaymentDate: '2024-09-30',
      dateCreated: '2024-09-28',
      bookings: [
        {
          id: 4,
          travelDate: '2024-12-15',
          clientFinalPaymentDate: '2024-12-01',
          supplierFinalPaymentDate: '2024-12-05',
          bookingDate: '2024-09-30',
          invoicedDate: '2024-09-30',
          confirmationNumbers: [{ confirmationNumber: 'CONF006', supplier: 'Adventure Trips' }],
          namesDateOfBirths: [{ name: 'Diana Prince', dateOfBirth: '1991-04-30' }],
          mailingAddress: '101 First Ave, Gotham, ON',
          phoneNumbers: ['555-3456'],
          emailAddresses: ['diana.prince@example.com'],
          significantDates: [],
          bookingId: '2024-10-07T21:51:07.345Z',
        },
        {
          id: 4,
          travelDate: '2025-03-10',
          clientFinalPaymentDate: '2025-02-25',
          supplierFinalPaymentDate: '2025-02-28',
          bookingDate: '2024-09-29',
          invoicedDate: '2024-09-29',
          confirmationNumbers: [{ confirmationNumber: 'CONF007', supplier: 'Mountain Tours' }],
          namesDateOfBirths: [{ name: 'Diana Prince', dateOfBirth: '1991-04-30' }],
          mailingAddress: '101 First Ave, Gotham, ON',
          phoneNumbers: ['555-3456'],
          emailAddresses: ['diana.prince@example.com'],
          significantDates: [],
          bookingId: '2024-10-07T21:51:08.678Z',
        },
      ],
    },
    {
      id: 5,
      clientName: 'Eve Adams',
      clientEmail: 'eve.adams@example.com',
      clientPhone: '555-7890',
      clientPostalCode: 'E5F 6G7',
      clientStreetAddress: '202 Second Ave',
      clientCity: 'Metropolis',
      clientProvince: 'QC',
      clientCountry: 'Canada',
      notes: 'Enjoys beach holidays.',
      invoiced: false,
      paid: false,
      paymentDate: '',
      finalPaymentDate: '',
      dateCreated: '2024-09-30',
      bookings: [
        {
          id: 5,
          travelDate: '2024-11-20',
          clientFinalPaymentDate: '2024-11-10',
          supplierFinalPaymentDate: '2024-11-15',
          bookingDate: '2024-10-01',
          invoicedDate: '2024-10-02',
          confirmationNumbers: [{ confirmationNumber: 'CONF008', supplier: 'Beach Holiday' }],
          namesDateOfBirths: [{ name: 'Eve Adams', dateOfBirth: '1993-07-05' }],
          mailingAddress: '202 Second Ave, Metropolis, QC',
          phoneNumbers: ['555-7890'],
          emailAddresses: ['eve.adams@example.com'],
          significantDates: [],
          bookingId: '2024-10-07T21:51:09.012Z',
        },
      ],
    },
    {
      id: 6,
      clientName: 'Frank Castle',
      clientEmail: 'frank.castle@example.com',
      clientPhone: '555-1230',
      clientPostalCode: 'F6G 7H8',
      clientStreetAddress: '303 Third Ave',
      clientCity: 'Star City',
      clientProvince: 'NS',
      clientCountry: 'Canada',
      notes: 'A big fan of road trips.',
      invoiced: true,
      paid: false,
      paymentDate: '',
      finalPaymentDate: '',
      dateCreated: '2024-10-01',
      bookings: [
        {
          id: 6,
          travelDate: '2024-10-30',
          clientFinalPaymentDate: '2024-10-20',
          supplierFinalPaymentDate: '2024-10-25',
          bookingDate: '2024-10-02',
          invoicedDate: '2024-10-03',
          confirmationNumbers: [{ confirmationNumber: 'CONF009', supplier: 'Road Trips Inc.' }],
          namesDateOfBirths: [{ name: 'Frank Castle', dateOfBirth: '1988-11-15' }],
          mailingAddress: '303 Third Ave, Star City, NS',
          phoneNumbers: ['555-1230'],
          emailAddresses: ['frank.castle@example.com'],
          significantDates: [],
          bookingId: '2024-10-07T21:51:10.345Z',
        },
        {
          id: 6,
          travelDate: '2025-05-10',
          clientFinalPaymentDate: '2025-05-01',
          supplierFinalPaymentDate: '2025-05-05',
          bookingDate: '2024-10-04',
          invoicedDate: '2024-10-05',
          confirmationNumbers: [{ confirmationNumber: 'CONF010', supplier: 'Adventure Travel' }],
          namesDateOfBirths: [{ name: 'Frank Castle', dateOfBirth: '1988-11-15' }],
          mailingAddress: '303 Third Ave, Star City, NS',
          phoneNumbers: ['555-1230'],
          emailAddresses: ['frank.castle@example.com'],
          significantDates: [],
          bookingId: '2024-10-07T21:51:11.678Z',
        },
      ],
    },
    {
      id: 7,
      clientName: 'Gina Gray',
      clientEmail: 'gina.gray@example.com',
      clientPhone: '555-4567',
      clientPostalCode: 'G7H 8I9',
      clientStreetAddress: '404 Fourth Ave',
      clientCity: 'Central City',
      clientProvince: 'NL',
      clientCountry: 'Canada',
      notes: 'Loves city breaks.',
      invoiced: false,
      paid: false,
      paymentDate: '',
      finalPaymentDate: '',
      dateCreated: '2024-10-05',
      bookings: [
        {
          id: 7,
          travelDate: '2024-12-05',
          clientFinalPaymentDate: '2024-11-25',
          supplierFinalPaymentDate: '2024-11-30',
          bookingDate: '2024-10-06',
          invoicedDate: '2024-10-07',
          confirmationNumbers: [{ confirmationNumber: 'CONF011', supplier: 'City Escapes' }],
          namesDateOfBirths: [{ name: 'Gina Gray', dateOfBirth: '1995-12-12' }],
          mailingAddress: '404 Fourth Ave, Central City, NL',
          phoneNumbers: ['555-4567'],
          emailAddresses: ['gina.gray@example.com'],
          significantDates: [],
          bookingId: '2024-10-07T21:51:12.901Z',
        },
      ],
    },
    {
      id: 8,
      clientName: 'Harry Hart',
      clientEmail: 'harry.hart@example.com',
      clientPhone: '555-8901',
      clientPostalCode: 'H8I 9J0',
      clientStreetAddress: '505 Fifth Ave',
      clientCity: 'Starling City',
      clientProvince: 'YT',
      clientCountry: 'Canada',
      notes: 'A nature lover.',
      invoiced: true,
      paid: true,
      paymentDate: '2024-10-01',
      finalPaymentDate: '2024-10-03',
      dateCreated: '2024-10-05',
      bookings: [
        {
          id: 8,
          travelDate: '2025-01-01',
          clientFinalPaymentDate: '2024-12-15',
          supplierFinalPaymentDate: '2024-12-20',
          bookingDate: '2024-10-05',
          invoicedDate: '2024-10-06',
          confirmationNumbers: [{ confirmationNumber: 'CONF012', supplier: 'Nature Tours' }],
          namesDateOfBirths: [{ name: 'Harry Hart', dateOfBirth: '1990-01-20' }],
          mailingAddress: '505 Fifth Ave, Starling City, YT',
          phoneNumbers: ['555-8901'],
          emailAddresses: ['harry.hart@example.com'],
          significantDates: [],
          bookingId: '2024-10-07T21:51:13.234Z',
        },
      ],
    },
    {
      id: 9,
      clientName: 'Ivy Pepper',
      clientEmail: 'ivy.pepper@example.com',
      clientPhone: '555-3450',
      clientPostalCode: 'I9J 0K1',
      clientStreetAddress: '606 Sixth Ave',
      clientCity: 'Bludhaven',
      clientProvince: 'AB',
      clientCountry: 'Canada',
      notes: 'Enjoys spa getaways.',
      invoiced: false,
      paid: false,
      paymentDate: '',
      finalPaymentDate: '',
      dateCreated: '2024-10-06',
      bookings: [
        {
          id: 9,
          travelDate: '2024-12-15',
          clientFinalPaymentDate: '2024-11-30',
          supplierFinalPaymentDate: '2024-12-05',
          bookingDate: '2024-10-07',
          invoicedDate: '2024-10-07',
          confirmationNumbers: [{ confirmationNumber: 'CONF013', supplier: 'Spa Retreat' }],
          namesDateOfBirths: [{ name: 'Ivy Pepper', dateOfBirth: '1989-05-05' }],
          mailingAddress: '606 Sixth Ave, Bludhaven, AB',
          phoneNumbers: ['555-3450'],
          emailAddresses: ['ivy.pepper@example.com'],
          significantDates: [],
          bookingId: '2024-10-07T21:51:14.567Z',
        },
      ],
    },
    {
      id: 10,
      clientName: 'Jack Frost',
      clientEmail: 'jack.frost@example.com',
      clientPhone: '555-9876',
      clientPostalCode: 'J0K 1L2',
      clientStreetAddress: '707 Seventh Ave',
      clientCity: 'Winterfell',
      clientProvince: 'SK',
      clientCountry: 'Canada',
      notes: 'A fan of winter sports.',
      invoiced: true,
      paid: false,
      paymentDate: '',
      finalPaymentDate: '',
      dateCreated: '2024-10-06',
      bookings: [
        {
          id: 10,
          travelDate: '2025-01-10',
          clientFinalPaymentDate: '2024-12-25',
          supplierFinalPaymentDate: '2024-12-30',
          bookingDate: '2024-10-06',
          invoicedDate: '2024-10-07',
          confirmationNumbers: [{ confirmationNumber: 'CONF014', supplier: 'Ski Resort' }],
          namesDateOfBirths: [{ name: 'Jack Frost', dateOfBirth: '1992-02-15' }],
          mailingAddress: '707 Seventh Ave, Winterfell, SK',
          phoneNumbers: ['555-9876'],
          emailAddresses: ['jack.frost@example.com'],
          significantDates: [],
          bookingId: '2024-10-07T21:51:15.890Z',
        },
      ],
    },
  ];
  